### PR TITLE
first commit of initial structure

### PR DESCRIPTION
**Pull request by lollcat**
Solves #1

### CODE REVIEW

**Comment by VincentStimper** [comment]
Looks pretty good! We can also make this installable with the setup I just committed. However, I would prefer using the modules I defined in https://github.com/VincentStimper/normalizing-flows for the flows. I also defined the target and the base distribution there and the learnt distribution is a normalizing flow model. The loss could then just be defined as a function taking the model and the target distribution as well as hyperparameters as input.

**Comment by lollcat** [comment]
@VincentStimper the code could still be much cleaner (I have made #5 to fix this), but all the base functionality is ready and the code is working on simple 2D problems. Could you let me know if you have any feedback on the code? I am going to run some more tests with some harder problems (e.g. 16 dim Many Well problem) in early Jan.

**Comment by lollcat** [comment]
Current status of this PR: This sets up all the initial structure for the code and provides a simple example of running the code with a 2D Many Well problem. I have made a separate issue ( #7 ) for replicating the results on the 16 dim Many Well problem, and the 2D GMM problem - which is what I am going to work on next.

**Comment by VincentStimper** [comment]
I had a look and it looks pretty good! I'm going to merge it now and we can start a new development phase from here.

**Pull request merged**
